### PR TITLE
Use hostname rather than ip address

### PR DESCRIPTION
**Pull request by giorgiosironi**
Supports changing the instance size or rebooting it through Terraform, which will update the DNS entries.

Necessary to stabilize https://github.com/libero/libero/issues/96

### CODE REVIEW

**Review by stephenwf — APPROVED** [review]
Makes sense. Is there a list of hosts that are set up under the Libero domain somewhere?

**Comment by giorgiosironi** [comment]
Yes, they are managed via Infrastructure as Code:
https://github.com/libero/infrastructure/blob/master/tf/main.tf#L95-L126

**Comment by giorgiosironi** [comment]
https://github.com/libero/infrastructure/pull/12 stopped all containers so I merge this to attempt to deploy them again.

**Comment by giorgiosironi** [comment]
Containers started, but [one smoke test failed](https://travis-ci.com/libero/environments/builds/104551193):
```
+ echo 'Smoke testing dummy-api'
++ curl -sS -H 'Host: unstable--dummy-api.libero.pub' http://localhost:80/ping
+ [[ curl: (7) Failed to connect to localhost port 80: Connection refused == \p\o\n\g ]]
```

**Comment by giorgiosironi** [comment]
Ah, the environment lost the customization `PUBLIC_PORT_BROWSER=80` because `/tmp` was cleared on reboot. Have to change folder.

**Pull request merged**
