### PR TITLE
update expiring certificates

### PR DESCRIPTION
**Pull request by GiancarloFusiello**
In reference to https://github.com/libero/publisher/issues/251

### CODE REVIEW

**Comment by giorgiosironi** [comment]
```
$ openssl x509 -in files/unstable/https_certificate.pem -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            03:60:ff:44:c5:32:59:38:36:11:a2:81:20:2b:04:f4:69:ac
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
        Validity
            Not Before: Sep 23 13:21:05 2019 GMT
            Not After : Dec 22 13:21:05 2019 GMT
        Subject: CN = unstable.libero.pub
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:b6:db:41:4f:6c:76:ed:e1:2c:83:a1:5f:a1:15:
                    86:f4:a7:17:e5:48:6a:e0:b3:22:07:6b:20:c4:15:
                    fb:6b:b5:35:82:d3:49:d9:fd:07:c8:d8:a9:1d:aa:
                    11:b5:15:8e:0b:88:14:70:f6:18:56:0c:37:6c:3d:
                    af:01:fc:86:29:ef:45:c6:73:ff:71:58:36:99:f8:
                    c1:b1:52:da:11:a9:c3:3a:38:a9:61:bc:6c:ba:ca:
                    3c:75:e0:f7:c0:01:d9:b8:99:6b:96:2e:c6:af:ae:
                    5c:53:f1:c4:45:88:f4:35:46:b5:67:1c:66:73:1d:
                    d8:d1:aa:78:b3:da:18:c2:12:5d:24:a1:ca:d1:4d:
                    3b:60:45:a3:c1:86:c5:e8:18:0d:51:9e:69:15:f5:
                    a7:2b:4a:5e:7c:cb:69:c0:eb:7a:6c:73:99:50:80:
                    a4:26:97:cd:e4:67:68:1f:28:64:4a:4b:f6:20:98:
                    d0:41:83:4e:f4:39:46:a4:ed:1b:39:b4:e4:6c:f0:
                    57:a4:a8:30:8c:35:9a:ab:ed:08:cf:40:f1:fa:67:
                    18:50:43:7b:f1:7b:33:a5:08:cd:bf:6e:f4:24:d9:
                    18:29:fe:7c:91:fd:14:ab:44:3a:d9:1a:89:f7:0c:
                    d9:16:74:7b:86:ee:86:1d:24:00:b1:f4:8f:6c:c1:
                    01:df
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier: 
                8F:86:AF:8B:C1:98:D9:8D:17:2D:8F:A1:32:1E:0B:02:84:86:E5:4A
            X509v3 Authority Key Identifier: 
                keyid:A8:4A:6A:63:04:7D:DD:BA:E6:D1:39:B7:A6:45:65:EF:F3:A8:EC:A1

            Authority Information Access: 
                OCSP - URI:http://ocsp.int-x3.letsencrypt.org
                CA Issuers - URI:http://cert.int-x3.letsencrypt.org/

            X509v3 Subject Alternative Name: 
                DNS:unstable--api-gateway.libero.pub, DNS:unstable--dummy-api.libero.pub, DNS:unstable--jats-ingester.libero.pub, DNS:unstable--pattern-library.libero.pub, DNS:unstable.libero.pub
            X509v3 Certificate Policies: 
                Policy: 2.23.140.1.2.1
                Policy: 1.3.6.1.4.1.44947.1.1.1
                  CPS: http://cps.letsencrypt.org

            CT Precertificate SCTs: 
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : E2:69:4B:AE:26:E8:E9:40:09:E8:86:1B:B6:3B:83:D4:
                                3E:E7:FE:74:88:FB:A4:8F:28:93:01:9D:DD:F1:DB:FE
                    Timestamp : Sep 23 14:21:05.949 2019 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:44:02:20:38:9C:61:7E:94:CB:16:1C:81:C1:E3:FA:
                                9E:B1:6A:08:09:2F:1D:A2:A9:E0:FF:86:80:68:37:FF:
                                B0:23:68:E9:02:20:5E:7D:9F:37:8D:DE:CA:34:7B:6A:
                                A0:E1:27:38:D0:F6:9F:EE:C3:67:43:9F:A2:1D:F1:02:
                                DB:51:25:8B:68:7E
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : 29:3C:51:96:54:C8:39:65:BA:AA:50:FC:58:07:D4:B7:
                                6F:BF:58:7A:29:72:DC:A4:C3:0C:F4:E5:45:47:F4:78
                    Timestamp : Sep 23 14:21:05.485 2019 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:44:02:20:67:B8:5D:EE:D2:B8:11:43:21:F6:78:24:
                                3B:36:58:F0:FD:CB:74:24:9E:22:CF:B2:1B:61:D5:FA:
                                C7:0E:55:7A:02:20:75:97:EC:D2:17:D0:33:FA:F0:25:
                                AB:8D:83:20:47:D4:7C:BE:7E:2A:28:E1:0B:E6:23:E2:
                                08:0B:85:FA:DF:11
    Signature Algorithm: sha256WithRSAEncryption
         50:0f:7c:f2:7f:d4:15:88:f4:dd:e9:c4:99:81:e3:b5:3b:56:
         58:1e:65:d3:bc:d6:d3:ed:39:c5:28:9f:b9:26:83:20:6b:ee:
         9b:a2:a9:8f:f7:5b:a8:82:65:82:49:3e:40:ea:a0:f7:cf:c0:
         3d:44:a9:88:8b:90:c5:2b:af:28:92:45:48:37:03:5a:f7:af:
         34:27:df:86:a3:bc:99:3f:c0:65:29:47:07:6e:f4:7b:9e:d1:
         1b:bc:e6:24:58:38:f8:45:98:ee:e4:56:25:9c:e0:6f:f0:cf:
         9b:a6:b4:10:f5:3a:32:ff:5d:99:a3:db:54:a0:d9:aa:6f:29:
         cb:c2:d4:f4:8a:e6:04:15:9b:8f:bc:27:e5:6b:e2:2f:ea:29:
         b8:a3:18:7e:95:cb:98:10:a3:a2:09:62:d7:a0:dc:3b:8b:8a:
         2b:f3:b8:a4:3f:27:1b:86:f3:c8:a4:6a:9e:0d:00:b3:53:09:
         99:e4:68:4d:69:91:8d:97:30:29:1c:25:a5:cd:2e:c8:ef:0c:
         4e:9c:0c:97:db:c1:2f:97:36:cc:bb:48:2a:e3:94:f4:51:7f:
         ad:65:04:e9:60:73:f1:ef:ed:df:ae:17:9f:35:45:6d:13:8a:
         2e:82:8f:ea:77:48:8a:5f:d1:5e:d3:ac:8f:96:e8:da:a2:ff:
         ed:bd:2b:b3
-----BEGIN CERTIFICATE-----
...
```

**Comment by giorgiosironi** [comment]
```
$ openssl x509 -in files/demo/https_certificate.pem -text
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            03:89:7b:ef:67:be:59:7c:ec:43:3f:46:da:73:da:a5:cc:b1
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
        Validity
            Not Before: Sep 25 08:05:15 2019 GMT
            Not After : Dec 24 08:05:15 2019 GMT
        Subject: CN = demo.libero.pub
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (2048 bit)
                Modulus:
                    00:df:35:9d:71:9f:f9:90:90:3a:ad:cb:2e:af:da:
                    d9:d2:5e:19:47:20:8e:1e:52:6e:a4:74:84:ad:27:
                    87:a2:1b:6d:63:16:1f:fc:7d:3c:85:9d:d7:c7:ed:
                    1c:6e:43:fb:2c:cb:b4:79:83:da:41:63:7e:ca:4c:
                    3e:a1:73:76:02:b8:9d:0c:5d:a0:b9:06:6c:12:9e:
                    ae:ed:48:70:e7:d3:cb:ad:a3:39:54:4a:d2:3b:bf:
                    94:87:7d:f3:ce:a8:5c:bb:35:a1:26:aa:ff:e5:b6:
                    17:7b:23:5e:2a:a5:3e:e0:78:93:cd:eb:55:be:a9:
                    c5:a1:d1:67:cc:db:30:45:76:d2:08:89:75:3b:bd:
                    82:ab:18:66:b8:a6:13:0e:76:09:55:ec:ca:58:6e:
                    b3:2e:b6:c2:21:ab:3d:7c:22:ed:8a:d0:59:dc:86:
                    f1:d3:c7:c0:c9:b2:d7:16:8d:15:38:6c:33:c6:1c:
                    1a:0a:ab:77:75:69:47:4a:5b:90:87:81:9f:ab:ee:
                    ac:6c:10:0f:65:55:27:bb:38:e8:74:15:bd:b2:c6:
                    e5:97:32:b7:c2:5e:78:9a:ab:10:65:ac:cc:0a:0c:
                    b4:da:aa:f2:8a:5d:55:f2:4c:5a:f2:d3:38:c3:74:
                    7f:94:6c:a0:82:67:0d:f6:49:aa:b1:1f:0b:ba:a9:
                    03:53
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Key Identifier: 
                AF:71:F7:DE:85:4C:ED:EB:24:75:CD:1F:CF:75:EC:15:22:B9:65:F6
            X509v3 Authority Key Identifier: 
                keyid:A8:4A:6A:63:04:7D:DD:BA:E6:D1:39:B7:A6:45:65:EF:F3:A8:EC:A1

            Authority Information Access: 
                OCSP - URI:http://ocsp.int-x3.letsencrypt.org
                CA Issuers - URI:http://cert.int-x3.letsencrypt.org/

            X509v3 Subject Alternative Name: 
                DNS:demo--api-gateway.libero.pub, DNS:demo--dummy-api.libero.pub, DNS:demo--jats-ingester.libero.pub, DNS:demo--pattern-library.libero.pub, DNS:demo.libero.pub
            X509v3 Certificate Policies: 
                Policy: 2.23.140.1.2.1
                Policy: 1.3.6.1.4.1.44947.1.1.1
                  CPS: http://cps.letsencrypt.org

            CT Precertificate SCTs: 
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : 74:7E:DA:83:31:AD:33:10:91:21:9C:CE:25:4F:42:70:
                                C2:BF:FD:5E:42:20:08:C6:37:35:79:E6:10:7B:CC:56
                    Timestamp : Sep 25 09:05:15.139 2019 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:45:02:20:16:8E:C4:9A:11:46:0E:10:76:8C:64:1F:
                                92:A3:9A:4A:C6:11:0D:F3:63:D6:97:A3:DD:A7:12:60:
                                AC:14:D6:66:02:21:00:EB:74:05:CB:FC:42:E3:33:DA:
                                C5:66:6F:B0:86:80:A8:62:62:D5:3F:08:27:0D:D6:83:
                                CC:1F:22:D3:B8:EC:3E
                Signed Certificate Timestamp:
                    Version   : v1 (0x0)
                    Log ID    : 29:3C:51:96:54:C8:39:65:BA:AA:50:FC:58:07:D4:B7:
                                6F:BF:58:7A:29:72:DC:A4:C3:0C:F4:E5:45:47:F4:78
                    Timestamp : Sep 25 09:05:15.132 2019 GMT
                    Extensions: none
                    Signature : ecdsa-with-SHA256
                                30:45:02:21:00:DA:6B:7F:E6:35:06:6D:AD:24:55:25:
                                78:FF:F4:72:B4:28:68:DE:C5:EE:03:0B:98:D9:5D:B7:
                                7B:98:5F:E6:AF:02:20:56:C3:E9:F5:31:E0:D7:EA:16:
                                66:F2:65:AB:A7:2E:A6:55:D4:F3:77:D4:94:AB:7F:67:
                                E8:4C:CD:97:8A:D0:6A
    Signature Algorithm: sha256WithRSAEncryption
         38:e0:e5:c7:82:5c:be:2b:33:89:6a:0f:5e:96:ef:8f:27:0f:
         82:0b:e6:c2:05:9d:ce:b8:d6:c2:77:99:ee:22:1f:31:29:fd:
         e3:e2:6e:5e:bb:dc:91:b8:17:cf:8a:7b:f0:9a:0f:71:77:28:
         ee:3a:69:2e:d2:8b:78:d3:71:f4:e2:ad:ff:1d:66:f9:77:5e:
         0d:41:0a:07:ca:52:62:65:ef:f8:35:7d:5a:c0:61:be:f2:63:
         8b:26:43:16:ae:6c:09:1c:ac:20:49:d1:d3:a9:b5:d2:d0:ed:
         f6:f8:40:4c:c1:bf:5a:60:38:49:2a:9e:d4:b6:9d:96:85:76:
         18:a7:ae:b0:8c:3d:22:ee:44:25:2a:19:f0:13:9e:90:6a:d2:
         b1:f1:57:4f:59:fd:2a:64:9e:93:b3:ac:f6:31:61:2c:46:08:
         f9:0e:98:58:4a:a3:fb:c9:6b:87:b9:0d:63:c8:b0:0d:b0:39:
         e8:06:f1:27:ef:b0:f9:23:b1:92:f2:f1:23:5a:e2:f2:7a:82:
         15:eb:41:8c:0c:92:80:15:00:a5:89:a6:03:2e:7a:38:b9:37:
         1c:8b:73:83:2b:91:1c:00:12:d5:9d:eb:84:2d:5d:cb:fe:7e:
         81:8e:f2:f2:0e:23:5e:42:8a:59:96:b0:d9:79:02:a9:c0:d8:
         52:3f:e7:25
-----BEGIN CERTIFICATE-----
...
```

**Review by giorgiosironi — APPROVED** [review]

**Comment by giorgiosironi** [comment]
After `unstable`, needs to be released to `demo`.

**Comment by GiancarloFusiello** [comment]
@giorgiosironi happy for me to push a new tag or should I leave it with you?

**Comment by GiancarloFusiello** [comment]
Pushed tag `latest/20190925`

**Comment by giorgiosironi** [comment]
Yes, please go ahead.

**Pull request merged**
